name: Given

on:
  push:
    branches:
      - testBranch
  pull_request:
    branches:
      - testBranch
      
jobs:
  rate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Run Command
      working-directory: ./rate
      run: |
        ./run install
    - name: Test Command
      working-directory: ./rate
      run: |
        ./run test
    
