name: CI
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1
 
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
 
    - name: Build
      run: go build
 
    - uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
 
    - uses: actions/gcloud/cli@master
      with:
        args: "app deploy --quiet --project=APP_ENGINE_PROJECT_NAME"
