on:
  push:
    branches:
      - main

name: Deploy to Google App Engine

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: 'lexical-botany-331616'
          service_account_key: '9d3c285a6e48cc467f14ba1f57946e9bbd04b43e'

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
