name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5 #Probably want to change to 1 at some point (or want to better specify requirements/uses)

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file .github/workflows/environment.yml --name base
        conda install -c conda-forge google-cloud-firestore
        conda install -c conda-forge google-cloud-datastore
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest api/test_api.py
        
    #BEGIN GOOGLE APP ENGINE DEPLOYMENT:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        deliverables: api/app.yaml
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Curl Test
      run: curl "${{ steps.deploy.outputs.url }}/packages/"
    
    - name: Wget Test
      run: wget "${{ steps.deploy.outputs.url }}/packages/"
